### ISSUE TITLE
sshfs-static 64-bit?

### ISSUE THREAD

**Issue by wcgall** [macfusion-ng/macfusion2#39]
macOS Mojave doesn't like the version of sshfs-static in this version of MacFusion.
It gives a warning message to update, & lists sshfs-static as the problem in 

About This Mac > System Report > Legacy Software

Should sshfs-static be replaced?  Is there a 64-bit version?  Does it just need to be recompiled?  We have until the next version of macOS to fix it.

**Comment by tessus** [comment]
I created new static libs a while back #28 and they work on my system. For some reason @ElDeveloper can't get them to work, so it was never merged.

**Comment by wcgall** [comment]
Thanks.  I tried b3, but keep having to grant permissions:



for each "disk".

**Comment by tessus** [comment]
Ok, just to clarify, https://evermeet.cx/pub/macosx/macfusion/Macfusion.app.b3-sta.tar.gz works for you?

Well, it also worked for others. So I am not sure what is going on with @ElDeveloper's env.
Maybe we shoud merge it anyway and go from there when something is off.

**Comment by wcgall** [comment]
So far, haven’t done much testing.
Fork it?

**Comment by tessus** [comment]
> Fork it?

Nope, but @ElDeveloper also mentioned in #28 that we could merge it, if he's the only one wirh a problem. So, if the new static libs work for you as they do for some others and me, we should finally merge it.

**Comment by ElDeveloper** [comment]
@wcgall, just wanted to check if you've done more testing. If you can confirm things work for you, then let's merge #28. 👍

**Comment by wcgall** [comment]
Yes, I've used it as much as I normally do, with no more problems.
So I vote for merge.

**Comment by ElDeveloper** [comment]
Excellent, thanks! Merged 👍
