### ISSUE TITLE
I am not able to build 

### ISSUE THREAD

**Issue by Khsaleh** [macfusion-ng/macfusion2#43]
![screen shot 2019-01-25 at 2 19 23 pm](https://user-images.githubusercontent.com/5544123/51767732-3bb9b200-20ac-11e9-8797-6848b00d69b3.png)

**Comment by tessus** [comment]
Please note that you have to set the target `All`.
Compiling `MFCore` directly doesn't make any sense anyway (in most cases).

The reason for the error is that in the target `All` the file in question is generated, in all other targets it is not. (I didn't want to generate the same file 9 times.)

**Comment by ElDeveloper** [comment]
I am not able to reproduce this issue with the latest version on master.
